// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zhuguangfeng/go-chat/cmd/server/app"
	activity3 "github.com/zhuguangfeng/go-chat/internal/event/activity"
	activity2 "github.com/zhuguangfeng/go-chat/internal/handler/v1/activity"
	"github.com/zhuguangfeng/go-chat/internal/handler/v1/jwt"
	review2 "github.com/zhuguangfeng/go-chat/internal/handler/v1/review"
	user2 "github.com/zhuguangfeng/go-chat/internal/handler/v1/user"
	"github.com/zhuguangfeng/go-chat/internal/repository/cache"
	"github.com/zhuguangfeng/go-chat/internal/repository/dao"
	"github.com/zhuguangfeng/go-chat/internal/service/activity"
	"github.com/zhuguangfeng/go-chat/internal/service/review"
	"github.com/zhuguangfeng/go-chat/internal/service/user"
	"github.com/zhuguangfeng/go-chat/ioc"
)

// Injectors from wire.go:

func InitWebServer() *app.App {
	cmdable := ioc.InitRedisCmd()
	jwtHandler := jwt.NewJwtHandler(cmdable)
	logger := ioc.InitLogger()
	db := ioc.InitMysql()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userService := user.NewUserService(logger, userDao, userCache)
	userHandler := user2.NewUserHandler(jwtHandler, userService)
	activityDao := dao.NewActivityDao(db)
	client := ioc.InitEsClient()
	activityEsDao := dao.NewActivityEsDao(client)
	activityService := activity.NewActivityService(logger, activityDao, activityEsDao)
	activityHandler := activity2.NewActivityHandler(logger, activityService, userService)
	reviewDao := dao.NewReviewDao1(db)
	saramaClient := ioc.InitKafka()
	syncProducer := ioc.InitSaramaSyncProducer(saramaClient)
	producer := activity3.NewProducer(logger, syncProducer)
	reviewService := review.NewReviewService(logger, reviewDao, producer)
	reviewHandler := review2.NewReviewHandler(logger, reviewService, activityService, userService)
	v := ioc.InitGlobalMiddleware(logger, jwtHandler)
	engine := ioc.InitWebServer(userHandler, activityHandler, reviewHandler, v)
	activityConsumer := activity3.NewActivityConsumer(saramaClient, logger, activityEsDao)
	v2 := ioc.NewConsumers(activityConsumer)
	appApp := &app.App{
		Server:    engine,
		Consumers: v2,
	}
	return appApp
}
